using System.Collections.Generic;
using Grimoire.Line.Api.Webhook.Event;

namespace Grimoire.Line.Api.Webhook
{
    /// <summary>
    /// Webhook Event Objects
    /// These are JSON objects containing events generated by the LINE platform.
    /// </summary>
    // [Json]
    public record WebhookEvent
    {
        public string Destination { get; set; }
        public List<BaseEvent> Events { get; set; }
    }
}
